config/routes.rb
Intake::Application.routes.draw do

  resources :reports

  get '/login' => "sessions#new", as: "new_session"
  post '/login' => "sessions#create", as: "session"
  delete '/logout' => "sessions#destroy", as: "logout"
  match "logout", :to => "sessions#destroy"

  resources :entrants

  resources :contacts

  resources :shelters

  resources :schools

  root :to => 'home#index'
  
  
  match 'schoolssearch' => 'schools#search'

  match 'studentssearch' => 'students#search'
  
  match 'reportsentrantbyschool' => 'reports#entrantbyschool'

  match 'reportsentrantbyage' => 'reports#entrantbyage'
  
  match 'reportsentrantbyshelter' => 'reports#entrantbyshelter'

end

app/models/shelter.rb
class Shelter < ActiveRecord::Base
  attr_accessible :city, :phone, :sheltername, :state, :street, :zip
  
  has_many :entrants
  
  
  def self.search(search)
    if search
      where('lower(sheltername) like ?', "%#{search.downcase}%")
    else
      scoped
    end
  end
  
  
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

  before_filter :check_authentication
  def check_authentication
    if not session[:user_id]
      redirect_to new_session_url
    end
  end

  # GET /shelters
  # GET /shelters.json
  def index
    @shelters = Shelter.all
    @shelters = Shelter.paginate(:page => params[:page], :per_page =>10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shelters }
    end
  end

  # GET /shelters/1
  # GET /shelters/1.json
  def show
    @shelter = Shelter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shelter }
    end
  end

  # GET /shelters/new
  # GET /shelters/new.json
  def new
    @shelter = Shelter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shelter }
    end
  end

  # GET /shelters/1/edit
  def edit
    @shelter = Shelter.find(params[:id])
  end

  # POST /shelters
  # POST /shelters.json
  def create
    @shelter = Shelter.new(params[:shelter])

    respond_to do |format|
      if @shelter.save
        format.html { redirect_to @shelter, notice: 'Shelter was successfully created.' }
        format.json { render json: @shelter, status: :created, location: @shelter }
      else
        format.html { render action: "new" }
        format.json { render json: @shelter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shelters/1
  # PUT /shelters/1.json
  def update
    @shelter = Shelter.find(params[:id])

    respond_to do |format|
      if @shelter.update_attributes(params[:shelter])
        format.html { redirect_to @shelter, notice: 'Shelter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shelter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shelters/1
  # DELETE /shelters/1.json
  def destroy
    @shelter = Shelter.find(params[:id])
    @shelter.destroy

    respond_to do |format|
      format.html { redirect_to shelters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/views/shelters/_form.html.erb
<div class="form-horizontal">
<div class="control-group">

<%= form_for(@shelter) do |f| %>
  <% if @shelter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shelter.errors.count, "error") %> prohibited this shelter from being saved:</h2>

      <ul>
      <% @shelter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
   <label class="control-label"><%= f.label :sheltername, "Shelter" %></label>
   <div class="controls">
    <%= f.text_field :sheltername %>
    </div>
  </div>

  <div class="field">
    <label class="control-label"><%= f.label :street, " Address" %></label>
    <div class="controls">
    <%= f.text_field :street %>
  </div>
  </div>
  
  <div class="field">
   <label class="control-label"> <%= f.label :city %></label>
   <div class="controls">
    <%= f.text_field :city %>
  </div>
  </div>
  
  <div class="field">
    <label class="control-label"><%= f.label :state %></label>
    <div class="controls">
    <%= f.text_field :state %>
  </div>
  </div>
  
  <div class="field">
    <label class="control-label"><%= f.label :zip %></label>
        <div class="controls">
    <%= f.number_field :zip %>
  </div>
  </div>
  
  <div class="field">
    <label class="control-label"><%= f.label :phone %></label>
    <div class="controls">
    <%= f.text_field :phone %>
  </div>
  </div>
  
  <div class="controls">
  <div class="actions">
    <%= f.submit :class=> 'btn' %>
  </div>
  </div>
  
<% end %>

</div>
</div>

app/views/shelters/edit.html.erb
<h1>Editing Shelter</h1>



<div class="button">
<%= link_to 'Show', @shelter, :class=> 'btn' %> 
<%= link_to 'Back', shelters_path, :class=> 'btn' %>
</div>


<div class="well">
<div class="siformone">
<%= render 'form' %>
</div>
</div>

app/views/shelters/index.html.erb
<h1>Minneapolis Shelters</h1>

<div id="indexbtn" class="btn">
	<%= link_to 'New Shelter', new_shelter_path %>
</div>

<br />

<div class="span11 entrants-wrapper">

<table id="mytable" class="table table-condensed table-hover table-fixed-header">
<thead class="header">
  <tr>
    <th>Shelter</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Phone</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<% @shelters.each do |shelter| %>
  <tbody>
  <tr>
    <td><%= link_to shelter.sheltername, shelter %></td>
    <td><%= shelter.street %></td>
    <td><%= shelter.city %></td>
    <td><%= shelter.state %></td>
    <td><%= shelter.zip %></td>
    <td><%= shelter.phone %></td>
    <td><%= link_to 'Edit', edit_shelter_path(shelter), :class=> 'btn' %></td>
    <td><%= link_to 'Remove', shelter, method: :delete, data: { confirm: 'Are you sure?' }, :class=> 'btn btn-warning'  %></td>
  </tr>
  </tbody>
<% end %>
</table>
</div>

<br />

<div class="pagination pagination-centered">
<%= will_paginate @entrants %>
</div>

app/views/shelters/new.html.erb
<h1>New Shelter</h1>
<div class="button">
<%= link_to 'Back', shelters_path, :class=> 'btn'  %>
</div>


<div class="well">
<div class="siformone">
<%= render 'form' %>
</div>
</div>

app/views/shelters/show.html.erb
<div class="button">
<%= link_to 'Edit', edit_shelter_path(@shelter), :class=> 'btn' %>
<%= link_to 'Shelters Table', shelters_path, :class=> 'btn' %>
</div>

<p id="notice"><%= notice %></p>

<div id="show" class="well lead">
<p>
  <b>Shelter:</b>
  <%= @shelter.sheltername %>
</p>

<p>
  <b>Address:</b>
  <%= @shelter.street %>
</p>

<p>
  <b>City:</b>
  <%= @shelter.city %>
</p>

<p>
  <b>State:</b>
  <%= @shelter.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @shelter.zip %>
</p>

<p>
  <b>Phone:</b>
  <%= @shelter.phone %>
</p>

</div>