config/routes.rb
Intake::Application.routes.draw do

  resources :reports

  get '/login' => "sessions#new", as: "new_session"
  post '/login' => "sessions#create", as: "session"
  delete '/logout' => "sessions#destroy", as: "logout"
  match "logout", :to => "sessions#destroy"

  resources :entrants

  resources :contacts

  resources :shelters

  resources :schools

  root :to => 'home#index'
  
  
  match 'schoolssearch' => 'schools#search'

  match 'studentssearch' => 'students#search'
  
  match 'reportsentrantbyschool' => 'reports#entrantbyschool'

  match 'reportsentrantbyage' => 'reports#entrantbyage'
  
  match 'reportsentrantbyshelter' => 'reports#entrantbyshelter'

end

app/models/entrant.rb
class Entrant < ActiveRecord::Base
  attr_accessible :cnamef, :cnamel, :contact_id, :dob, :grade, :lastschool_id, :mnres, :mpsschool_id, :nonmpsschool, :note, :shelterid, :shelterschool, :studentid, :bus, :lastcity, :laststate, :discovery, :transport, :language, :stays_attributes, :entrants_needs_attributes, :needs_attributes, :needs, :contact_attributes

  has_many :stays
  has_many :needs, :through => :entrants_needs
  has_many :entrants_needs
  
  accepts_nested_attributes_for :stays
  accepts_nested_attributes_for :entrants_needs


  belongs_to :school
  belongs_to :lastschool, :foreign_key => "lastschool_id", :class_name => "School"
  belongs_to :mpsschool, :foreign_key => "mpsschool_id", :class_name => "School"
  belongs_to :shelter, :foreign_key => "shelterid", :class_name => "Shelter"
  belongs_to :contact


def days_between(entrydate, exitdate)


end

  def self.search(search)
    
    if search
    	if search.to_i == 0
				Entrant.joins(:contact).where('lower(contacts.pnamef) like ? OR lower(contacts.pnamel) like ? OR lower(cnamef) like ? OR lower(cnamel) like ?', "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%")    
			elsif search.to_i != 0 
				Entrant.where('studentid = ?', search.to_i)
			end
		else
      scoped
    end
  end

end

app/controllers/entrants_controller.rb
class EntrantsController < ApplicationController

  before_filter :check_authentication
  def check_authentication
    if not session[:user_id]
      redirect_to new_session_url
    end
  end


  # GET /entrants
  # GET /entrants.json
  def index
    @entrants = Entrant.paginate(:page => params[:page], :per_page =>10)
		
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entrants }
    end
  end

  # GET /entrants/1
  # GET /entrants/1.json
  def show
    @entrant = Entrant.find(params[:id])
    @shelters = Shelter.all
    @schools = School.all
    @stays = Stay.all
		@needs = @entrant.needs
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entrant }
    end
  end

  # GET /entrants/new
  # GET /entrants/new.json
  def new
    @entrant = Entrant.new
		@shelters = Shelter.all
		@schools = School.all
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entrant }
    end
  end

  # GET /entrants/1/edit
  def edit
    @entrant = Entrant.find(params[:id])
    @shelters = Shelter.all
    @schools = School.all

  end

  # POST /entrants
  # POST /entrants.json
  def create
    @entrant = Entrant.new(params[:entrant])
    @shelters = Shelter.all
    @schools = School.all

    respond_to do |format|
      if @entrant.save
        format.html { redirect_to @entrant, notice: 'Entrant was successfully created.' }
        format.json { render json: @entrant, status: :created, location: @entrant }
      else
        format.html { render action: "new" }
        format.json { render json: @entrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entrants/1
  # PUT /entrants/1.json
  def update
    @entrant = Entrant.find(params[:id])

    respond_to do |format|
      if @entrant.update_attributes(params[:entrant])
        format.html { redirect_to @entrant, notice: 'Entrant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrants/1
  # DELETE /entrants/1.json
  def destroy
    @entrant = Entrant.find(params[:id])
    @entrant.destroy

    respond_to do |format|
      format.html { redirect_to entrants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/entrants_helper.rb
module EntrantsHelper
end

app/views/entrants/_form.html.erb
<div class="form-horizontal">
<div class="control-group">

<%= form_for(@entrant) do |f| %>
  <% if @entrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entrant.errors.count, "error") %> prohibited this entrant from being saved:</h2>

      <ul>
      <% @entrant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="two-col">
  <div class="field">
     <label class="control-label"><%= f.label :cnamef, "Child's First Name" %></label>
   <div class="controls"> 
    <%= f.text_field :cnamef %>
  </div>
  </div>
  
  
  <div class="field">
    <label class="control-label"><%= f.label :cnamel, "Child's Last Name" %></label>
     <div class="controls"> 
    <%= f.text_field :cnamel %>
  </div>
  </div>
 
  
  <div class="field">
  <label class="control-label">
    <%= f.label :contact_id, "Contact" %></label>
  <div class="controls"> 
    <%= f.number_field :contact_id %>
  </div>
	</div>

	
  
  <div class="field">
  <label class="control-label">
    <%= f.label :dob, "Date of Birth" %></label>
    <div class="controls"> 
    <%= f.date_select :dob, :start_year => 1990 %>
  </div>
  </div>
  

  <div class="field"> 
  <label class="control-label">
    <%= f.label :grade, "Grade" %></label>
  <div class="controls"> 
    <%= f.select :grade, options_for_select(["Pre-K","K","1","2","3","4","5","6","7","8","9","10","11","12"]) %>
  </div>
  </div>
  
  <div class="field">
  <label class="control-label">
    <%= f.label :shelterid, "Shelter" %></label>
    <div class="controls"> 
    <%= f.select :shelterid, options_from_collection_for_select(@shelters, 'id', 'sheltername')  %>
  </div>
  </div>
  
  <div class="field"> 
  <label class="control-label">
    <%= f.label :mnres, "MN Res" %></label>
  <div class="controls"> 
    <%= f.select :mnres, options_for_select(["Yes","No"]) %>
  </div>
  </div>

  
  <div class="field">
  <label class="control-label"><%= f.label :laststate, "Last State" %></label>
  <div class="controls"> 
    <%= f.text_field :laststate %>
  </div>
  </div>
  
  <div class="field">
  <label class="control-label"><%= f.label :lastcity, "Last City" %></label>
  <div class="controls"> 
    <%= f.text_field :lastcity %>
  </div>
  </div>
  
  <div class="field">
    <label class="control-label">
    <%= f.label :lastschool, "Last School" %></label>
  <div class="controls"> 
  <%= f.select :id, options_from_collection_for_select(@schools, 'id', 'schoolname'), :include_blank => 'NA'  %>
  </div>
  </div>
  
  <div class="field">
  <label class="control-label">
    <%= f.label :studentid, "studentid" %></label>
  <div class="controls"> 
    <%= f.number_field :studentid %>
  </div>
	</div>

  <div class="field"> 
  <label class="control-label">
    <%= f.label :bus, "Bus" %></label>
  <div class="controls"> 
    <%= f.select :bus, options_for_select(["Yes","No"]) %>
  </div>
  </div>

  <div class="field"> 
  <label class="control-label">
    <%= f.label :needs, "Needs" %></label>
  <div class="controls"> 
    <%= f.select :needs, options_for_select(["Yes","No"]) %>
  </div>
  </div>
	
	<div class="field"> 
  <label class="control-label">
    <%= f.label :discovery, "Discovery" %></label>
  <div class="controls"> 
    <%= f.select :discovery, options_for_select(["Yes","No"]) %>
  </div>
  </div>
	
  <div class="field"> 
  <label class="control-label">
    <%= f.label :transport, "Transport" %></label>
  <div class="controls"> 
    <%= f.select :transport, options_for_select(["Yes","No"]) %>
  </div>
  </div>

    
  <div class="field">
        <label class="control-label">
    <%= f.label :note, "Notes" %></label>
      <div class="controls"> 
    <%= f.text_area :note %>
    </div>
  </div>

</div>  

  <div class="controls"> 
  <div class="actions">
    <%= f.submit :class=> 'btn'%>
  </div>
  </div>
  
<% end %>

</div>
</div>

app/views/entrants/edit.html.erb
<h1>Editing Entrant</h1>

<div class="two-col">
<div id="show" class="well">

<%= render 'form' %>

<%= link_to 'Show', @entrant %> |
<%= link_to 'Back', entrants_path %>
</div>
</div>

app/views/entrants/index.html.erb
<!-- <td colspan="3" style="text-align:center;" -->

<h1>Entrants</h1>

<div id="indexbtn" class="btn">
<%= link_to 'New Entrant', new_contact_path %>
</div>


<div class="span11 entrants-wrapper">

<table id="mytable" class="table table-condensed table-hover table-fixed-header">
<thead class="header">
  <tr>
    <th>Child's First Name</th>
    <th>Child's Last Name</th>
    <th>Guardian</th>
    <th>Date of Birth</th>
    <th>Grade</th>
    <th>ID</th>
    <th>Shelter</th>
		<th>Bus Needed</th>
		<th>Entered in Discovery</th>
		<th>Transport Setup</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
</div>

<% @entrants.each do |entrant| %>
  <tr>
    <td><%= link_to entrant.cnamef, entrant %></td>
    <td><%= link_to entrant.cnamel, entrant %></td>
    
    <td>    	<% if(entrant.contact_id.nil?) then %>
    		NA
    	<% else %>
    		<div id="<%= entrant.id %>" class="pop">
        	<%= link_to entrant.contact.pnamef + " " + entrant.contact.pnamel, contact_path(entrant.contact.id) %>
        </div>
        <div id="hide-<%= entrant.id %>" class="hide">
        <%= entrant.contact.pnamef %>
        <%= entrant.contact.pnamel %>
        <%= entrant.contact.phone %>
        </div>
      <% end %></td>
    
    <td class="dob"><%= entrant.dob %></td>
    <td><%= entrant.grade %></td>
    <td><%= entrant.studentid%></td>
    
    <td><% if(entrant.shelterid.nil?) then %>
    		NA
    	<% else %>   
            <%= link_to Shelter.find(entrant.shelterid).sheltername, shelter_path(entrant.shelterid) %>
      <% end %>
      </td>
    <td><%= entrant.bus %></td>
    <td><%= entrant.discovery %></td>
    <td><%= entrant.transport %></td>

    <td class="note"><%= entrant.note %></td>
    <td><%= link_to 'Edit', edit_contact_path(entrant), :class=> 'btn' %></td>
    <td><%= link_to 'Remove', entrant, method: :delete, data: { confirm: 'Are you sure?' }, :class=> 'btn btn-warning'  %></td>
  </tr>
<% end %>
</table>
</div>
<br />

<div class="pagination pagination-centered">
<%= will_paginate @entrants %>
</div>

app/views/entrants/new.html.erb
<h1>New Child</h1>

<div class="well">

<%= render 'form' %>

<%= link_to 'Back', entrants_path, :class=> 'btn'%>

</div>

app/views/entrants/search.html.erb
<div id="page">
<div id="searchtitle" class="well">
<h2>Search Results</h2>
</div>

<% if @entrants.empty? %>

  <h3 class="alert">No entrants with that name.</h3>  

<% else%>

<div class="span11 entrants-wrapper">


<table class="table table-condensed table-hover table-fixed-header">
	<thead class="header">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Last Name</th>
    <th>Last Name</th>
    <th>Date of Birth</th>
    <th>Grade</th>
    <th>School</th>
    <th>Last Name</th>
  	<th>Last Name</th>
    <th>Last Name</th>
    <th>Last Name</th>
  	<th>Last Name</th>
    <th>Last Name</th>
    <th>Last Name</th>
    <th>Last Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
	</thead>
<% @entrants.each do |entrant| %>
  <tr>
    <td><%= entrant.cnamef %></td>
    <td><%= entrant.cnamel %></td>
    <td><%= entrant.contact_id %></td>
    <td><%= entrant.dob %></td>
    <td><%= entrant.entrydate %></td>
    <td><%= entrant.exitdate %></td>
    <td><%= entrant.grade %></td>
    <td><%= entrant.lastschool %></td>
    <td><%= entrant.mnres %></td>
    <td><%= entrant.mpsschool %></td>
    <td><%= entrant.nonmpsschool %></td>
    <td><%= entrant.note %></td>
    <td><%= entrant.shelterid %></td>
    <td><%= entrant.shelterschool %></td>
    <td><%= entrant.totaldays %></td>
    <td><% if(entrant.school.nil?) then %>
    The entrant has no school to speak of.
  <% else %>
    <%= entrant.school.name %>
  <% end %></td>
    <td><%= link_to 'Show', entrant %></td>
    <td><%= link_to 'Edit', edit_entrant_path(entrant) %></td>
    <td><%= link_to 'Destroy', entrant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>

<% end %>
<div class="btn">
<%= link_to 'Back', root_path %>
</div>

</div>

app/views/entrants/show.html.erb
<div class="button">
<%= link_to 'Edit', edit_contact_path(@entrant.contact), :class=> 'btn' %>
<%= link_to 'Entrants Table', entrants_path, :class=> 'btn' %>
</div>

<div id="show" class="well lead">

<p id="notice"><%= notice %></p>

<p>
  <b>Child's First Name:</b>
  <%= @entrant.cnamef %>
</p>

<p>
  <b>Child's Last Name:</b>
  <%= @entrant.cnamel %>
</p>

<p>
  <div id="<%= @entrant.id %>" class="pop">
  <b>Guardian:</b>
      <% if(@entrant.contact.nil?) then %>
    		NA
  <% else %>
        <%= link_to @entrant.contact.pnamef + " " + @entrant.contact.pnamel, contact_path(@entrant.contact.id) %>
    </div>
    <div id="hide-<%= @entrant.id %>" class="hide">
        <%= @entrant.contact.street %>
        <%= @entrant.contact.city %>
        <%= @entrant.contact.state %>
        <%= @entrant.contact.zip %>
        </br>
        <%= @entrant.contact.phone %>
        </div>
  <% end %>
</p>



<p>
  <b>Date of Birth:</b>
  <%= @entrant.dob %>
</p>

<p>
  <b>Grade:</b>
  <%= @entrant.grade %>
</p>

<p>
  <b>Student ID:</b>
  <%= @entrant.studentid %>
</p>

<p>
  <b>Shelter:</b>
  	<% if(@entrant.shelterid.nil?) then %>
    		NA
  <% else %>   
  	<%= link_to Shelter.find(@entrant.shelterid).sheltername, shelter_path(@entrant.shelterid) %>
  <% end %>
</p>

<p>
  <b>MN Res:</b>
  <%= @entrant.mnres %>
</p>

<p>
  <b>Last State:</b>
  <%= @entrant.laststate %>
</p>

<p>
  <b>Last City:</b>
  <%= @entrant.lastcity %>
</p>

<p>
  <b>Last School:</b>
  <% if(@entrant.lastschool.nil?) then %>
			NA
  <% else %>  
    <%= @entrant.lastschool.schoolname %>
  <% end %>
</p>

<p>
  <b>Current School:</b>
  <% if(@entrant.mpsschool.nil?) then %>
			NA
  <% else %>  
    <%= @entrant.mpsschool.schoolname %>
  <% end %>
</p>

<p>
  <b>Special Needs:</b>
  	<% if (@needs.nil?) then %>
    		NA
  <% else %>   
		<% @needs.each do |bob| %>
				<%= bob.item %>
		<% end %>
  <% end %>
</p>
  
  	
<p>
	<b>Language:</b>
	<%= @entrant.language %>
</p>

<p>
  <b>Bus:</b>
  <%= @entrant.bus %>
</p>


<p>
  <b>Discovery:</b>
  <%= @entrant.discovery %>
</p>

<p>
  <b>Transport:</b>
  <%= @entrant.transport %>
</p>

<p>
  <b>Note:</b>
  <%= @entrant.note %>
</p>


</div>