config/routes.rb
Intake::Application.routes.draw do

  resources :reports

  get '/login' => "sessions#new", as: "new_session"
  post '/login' => "sessions#create", as: "session"
  delete '/logout' => "sessions#destroy", as: "logout"
  match "logout", :to => "sessions#destroy"

  resources :entrants

  resources :contacts

  resources :shelters

  resources :schools

  root :to => 'home#index'
  
  
  match 'schoolssearch' => 'schools#search'

  match 'studentssearch' => 'students#search'
  
  match 'reportsentrantbyschool' => 'reports#entrantbyschool'

  match 'reportsentrantbyage' => 'reports#entrantbyage'
  
  match 'reportsentrantbyshelter' => 'reports#entrantbyshelter'

end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :city, :officephone, :schoolname, :sswname, :sswphone, :state, :street, :zip
  

  
  def self.search(search)
    if search
      where('lower(schoolname) like ?', "%#{search.downcase}%")

    else
      scoped
    end
  end
  
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  before_filter :check_authentication
  def check_authentication
    if not session[:user_id]
      redirect_to new_session_url
    end
  end

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.paginate(:page => params[:page], :per_page =>10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end
  
  def search
    	@schools = School.search(params[:search])
    	@entrants = Entrant.search(params[:search])
  		@contacts = Contact.search(params[:search])
  		@shelters = Shelter.search(params[:search])
  end
	
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<div class="form-horizontal">
<div class="control-group">

<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="two-col">
  <div class="field">
    <label class="control-label"><%= f.label :schoolname, "School Name" %></label>
  	<div class="controls"><%= f.text_field :schoolname %></div>
  </div>
  <div class="field">
    <label class="control-label"><%= f.label :street, "Address" %></label>
    <div class="controls"><%= f.text_field :street %></div>
  </div>
  <div class="field">
    <label class="control-label"><%= f.label :city, "City" %></label>
    <div class="controls"><%= f.text_field :city %></div>
  </div>
  <div class="field">
    <label class="control-label"><%= f.label :state, "State" %></label>
    <div class="controls"><%= f.text_field :state %></div>
  </div>
  <div class="field">
    <label class="control-label"><%= f.label :zip, "Zip" %></label>
    <div class="controls"><%= f.number_field :zip %></div>
  </div>
  <div class="field">
    <label class="control-label"><%= f.label :officephone, "Office Phone" %></label>
    <div class="controls"><%= f.text_field :officephone %></div>
  </div>
  <div class="field">
    <label class="control-label"><%= f.label :sswname, "Social Worker Name" %></label>
    <div class="controls"><%= f.text_field :sswname %></div>
  </div>
  <div class="field">
    <label class="control-label"><%= f.label :sswphone, "Social Worker Phone" %></label>
    <div class="controls"><%= f.text_field :sswphone %></div>
  </div>
  <div class="controls"> 
  <div class="actions">
    <%= f.submit :class=> 'btn'%>
  </div>
  </div>
<% end %>

</div>
</div>

app/views/schools/edit.html.erb
<h1>Editing School</h1>
<div class="button">
<%= link_to 'Show', @school, :class=> 'btn' %>
<%= link_to 'Back', schools_path, :class=> 'btn'  %>
</div>

<div class="well">
<div class="siform">
<%= render 'form' %>
</div>
</div>

app/views/schools/index.html.erb
<h1>Schools</h1>

<div id="indexbtn" class="btn">
<%= link_to 'New School', new_school_path %>
</div>

<div class="span11 entrants-wrapper">

<table class="table table-condensed table-hover">
  <tr>
    <th>School Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Office Phone</th>
    <th>Social Worker Name</th>
    <th>Social Worker Phone</th>
    <th></th>
    <th></th>
  </tr>

<% @schools.each do |school| %>
  <tr>
    <td><%= link_to school.schoolname, school %></td>
    <td><%= school.street %></td>
    <td><%= school.city %></td>
    <td><%= school.state %></td>
    <td><%= school.zip %></td>
    <td><%= school.officephone %></td>
    <td><%= school.sswname %></td>
    <td><%= school.sswphone %></td>
    <td><%= link_to 'Edit', edit_school_path(school), :class=> 'btn'  %></td>
    <td><%= link_to 'Remove', school, method: :delete, data: { confirm: 'Are you sure?' }, :class=> 'btn btn-warning'  %></td>
  </tr>
<% end %>
</table>
</div>

<br />
<div class="pagination pagination-centered">
<%= will_paginate @entrants %>
</div>

app/views/schools/new.html.erb
<h1>New School</h1>
<div class="button">
<%= link_to 'Back', schools_path, :class=> 'btn' %>
<%= link_to 'Entrant', entrants_path, :class=> 'btn' %>
</div>


<div class="well">
<div class="siform">
<%= render 'form' %>
</div>
</div>

app/views/schools/search.html.erb
<body>
<div id="page">

	<div id="searchtitle" class="well">
		<h2>Search Results</h2>
	</div>

	<div class="span11">
	
	<div class="entrantsearch">
		<% if @entrants.empty? %>
  <h3 class="alert">No names found matching your search.</h3>  
	<% else%>
	<div class="entrants-wrapper">
	<table class="table table-condensed table-hover ">
  	<tr>
    	<th>Child's First Name</th>
    	<th>Child's Last Name</th>
    	<th>Guardian</th>
    	<th>Date of Birth</th>
    	<th>Grade</th>
    	<th>Student ID</th>
    	<th>Shelter</th>
    	<th>Last School</th>
  		<th>Current School</th>
  	</tr>
	<% @entrants.each do |entrant| %>
  	<tr>
    	<td><%= link_to entrant.cnamef, entrant  %></td>
    	<td><div id="child-<%= entrant.id %>" class="pop">
    			<%= link_to entrant.cnamel, entrant  %>
    			</div>
    			<div id="hide-child-<%= entrant.id %>" class="hide">
        		Bus: <%= entrant.bus %>
    				Discovery: <%= entrant.discovery %>
    				Transport: <%= entrant.transport %>
    				Note: <%= entrant.note %>
        	</div>
    	</td>
    	<td><% if(entrant.contact_id.nil?) then %>
    				NA
    			<% else %>
    				<div id="<%= entrant.id %>" class="pop">
        		<%= link_to entrant.contact.pnamef + " " + entrant.contact.pnamel, contact_path(entrant.contact.id) %>
        		</div>
       		 	<div id="hide-<%= entrant.id %>" class="hide">
        		<%= entrant.contact.pnamef %>
        		<%= entrant.contact.pnamel %>
        		<%= entrant.contact.phone %>
        		</div>
      		<% end %>
      </td>
    	<td><%= entrant.dob %></td>
    	<td><%= entrant.grade %></td>
    	<td><%= entrant.studentid%></td>
      <td><% if(entrant.shelterid.nil?) then %>
    				NA
    			<% else %>   
            <%= link_to Shelter.find(entrant.shelterid).sheltername, shelter_path(entrant.shelterid) %>
      		<% end %>
      </td>
      
    	<td><% if(entrant.lastschool.nil?) then %>
					NA
  			<% else %>  
    			<%= link_to School.find(entrant.lastschool).schoolname, school_path(entrant.lastschool) %>
  			<% end %>
    	</td>
    	<td>
    	  <% if(entrant.mpsschool.nil?) then %>
					NA
  			<% else %>  
    			<%= link_to School.find(entrant.mpsschool).schoolname, school_path(entrant.mpsschool) %>
  			<% end %>
    	</td>
  	</tr>
	<% end %>
		</table>
		</div>	<!-- Entrants search -->
		<% end %>
</div>	<!-- Entrants search -->






	<div class = "schoolsearch">
		<% if @schools.empty? %>
		  <h3 class="alert">No schools found matching your search.</h3>  

		<% else%>
	<div class="entrants-wrapper">
	<table class="table table-condensed table-hover">
  	<tr>
    	<th>School Name</th>
    	<th>Phone</th>
    	<th>Social Worker</th>
    	<th>Social Worker Phone</th>

  </tr>
	<% @schools.each do |school| %>
  	<tr>
    	<td>
    		<div id="school-<%= school.id %>" class="pop">
        	<%= link_to school.schoolname, school %>
        </div>
        <div id="hide-school-<%= school.id %>" class="hide">
        <%= school.street %>
        <%= school.city %>
        <%= school.state %>
        <%= school.zip %>
        </div>
      </td>
    	<td><%= school.officephone %></td>
    	<td><%= school.sswname %></td>
    	<td><%= school.sswphone %></td>
  	</tr>
	<% end %>
		</table>
		</div> <!-- entrants wrapper -->
	<% end %>
</div><!-- School search -->


	<div class = "sheltersearch">
		<% if @shelters.empty? %>
		  <h3 class="alert">No shelters found matching your search.</h3>  

		<% else%>
	<div class="entrants-wrapper">
	<table class="table table-condensed table-hover">
  	<tr>
    	<th>Shelter Name</th>
    	<th>Phone</th>
  </tr>
	<% @shelters.each do |shelter| %>
  	<tr>
    	<td>
    	<div id="shelter-<%= shelter.id %>" class="pop">
    		<%= link_to shelter.sheltername, shelter %>
    	</div> 	
    	<div id="hide-shelter-<%= shelter.id %>" class="hide">
    		<%= shelter.street %>
    		<%= shelter.city %>
    		<%= shelter.state %>
    		<%= shelter.zip %>
    	</div>
    	</td>
    	<td><%= shelter.phone %></td>
  	</tr>
	<% end %>
		</table>
		</div> <!-- entrants wrapper -->
	<% end %>
	</div><!-- shelter search -->


	
	</div> <!-- Span 11 -->
	
	
	</div> <!-- Page -->
</body>

app/views/schools/show.html.erb
<div class="button">
<%= link_to 'Edit', edit_school_path(@school), :class=> 'btn' %>
<%= link_to 'Schools Table', schools_path, :class=> 'btn' %>
</div>

<div id="show" class="well lead">

<p id="notice"><%= notice %></p>

<p>
  <b>School Name:</b>
  <%= @school.schoolname %>
</p>

<p>
  <b>Address:</b>
  <%= @school.street %>
</p>

<p>
  <b>City:</b>
  <%= @school.city %>
</p>

<p>
  <b>State:</b>
  <%= @school.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @school.zip %>
</p>

<p>
  <b>Office Phone:</b>
  <%= @school.officephone %>
</p>

<p>
  <b>Social Worker Name:</b>
  <%= @school.sswname %>
</p>

<p>
  <b>Social Worker Phone:</b>
  <%= @school.sswphone %>
</p>


</div>