config/routes.rb
Intake::Application.routes.draw do

  resources :reports

  get '/login' => "sessions#new", as: "new_session"
  post '/login' => "sessions#create", as: "session"
  delete '/logout' => "sessions#destroy", as: "logout"
  match "logout", :to => "sessions#destroy"

  resources :entrants

  resources :contacts

  resources :shelters

  resources :schools

  root :to => 'home#index'
  
  
  match 'schoolssearch' => 'schools#search'

  match 'studentssearch' => 'students#search'
  
  match 'reportsentrantbyschool' => 'reports#entrantbyschool'

  match 'reportsentrantbyage' => 'reports#entrantbyage'
  
  match 'reportsentrantbyshelter' => 'reports#entrantbyshelter'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :city, :phone, :pnamef, :pnamel, :state, :street, :zip, :entrants_attributes
    
  has_many :entrants
  
  accepts_nested_attributes_for :entrants

  def self.search(search)
    if search
      where("lower(pnamef) like ?", "%#{search.downcase}%")
    else
      scoped
    end
  end


end

app/models/entrant.rb
class Entrant < ActiveRecord::Base
  attr_accessible :cnamef, :cnamel, :contact_id, :dob, :grade, :lastschool_id, :mnres, :mpsschool_id, :nonmpsschool, :note, :shelterid, :shelterschool, :studentid, :bus, :lastcity, :laststate, :discovery, :transport, :language, :stays_attributes, :entrants_needs_attributes, :needs_attributes, :needs, :contact_attributes

  has_many :stays
  has_many :needs, :through => :entrants_needs
  has_many :entrants_needs
  
  accepts_nested_attributes_for :stays
  accepts_nested_attributes_for :entrants_needs


  belongs_to :school
  belongs_to :lastschool, :foreign_key => "lastschool_id", :class_name => "School"
  belongs_to :mpsschool, :foreign_key => "mpsschool_id", :class_name => "School"
  belongs_to :shelter, :foreign_key => "shelterid", :class_name => "Shelter"
  belongs_to :contact


def days_between(entrydate, exitdate)


end

  def self.search(search)
    
    if search
    	if search.to_i == 0
				Entrant.joins(:contact).where('lower(contacts.pnamef) like ? OR lower(contacts.pnamel) like ? OR lower(cnamef) like ? OR lower(cnamel) like ?', "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%")    
			elsif search.to_i != 0 
				Entrant.where('studentid = ?', search.to_i)
			end
		else
      scoped
    end
  end

end

app/models/entrants_need.rb
class EntrantsNeed < ActiveRecord::Base
  attr_accessible :need_id, :entrant_id 
  
  belongs_to :entrant
  belongs_to :need

  
end

app/models/need.rb
class Need < ActiveRecord::Base
  attr_accessible :item
  
	has_many :entrants, :through => :entrants_needs
	has_many :entrants_needs
  
end

app/models/report.rb
class Report < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :email, :name, :position, :reason
end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :city, :officephone, :schoolname, :sswname, :sswphone, :state, :street, :zip
  

  
  def self.search(search)
    if search
      where('lower(schoolname) like ?', "%#{search.downcase}%")

    else
      scoped
    end
  end
  
end

app/models/shelter.rb
class Shelter < ActiveRecord::Base
  attr_accessible :city, :phone, :sheltername, :state, :street, :zip
  
  has_many :entrants
  
  
  def self.search(search)
    if search
      where('lower(sheltername) like ?', "%#{search.downcase}%")
    else
      scoped
    end
  end
  
  
end

app/models/stay.rb
class Stay < ActiveRecord::Base
  attr_accessible :entrant_id, :shelter_id, :entrydate, :exitdate, :totaldays
  
  belongs_to :entrant

  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password_digest, :username
  
  has_secure_password
  validates_uniqueness_of :username

  def self.authenticate(username, password)
    user = User.find_by_username(username)
    if not user && user.authenticate(password)
      nil
    else
      return user
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

 
  before_filter :check_authentication
  def check_authentication
    if not session[:user_id]
      redirect_to new_session_url
    end
  end


  def index
  
  end

end

app/controllers/stays_controller.rb
class StaysController < ApplicationController

  before_filter :check_authentication
  def check_authentication
    if not session[:user_id]
      redirect_to new_session_url
    end
  end


  def index

  end
  
  def show

  end

  def new
    @stay = Stay.new
		@contact = Contact.new
		@entrant = Entrant.new
  end
  

  def edit

  end


  def create
    @stay = Stay.new(params[:stay])
    @contact = Contact.new
    @entrant = Entrant.new

    respond_to do |format|
      if @stay.save
        format.html { redirect_to @stay, notice: 'Entrant was successfully created.' }
        format.json { render json: @stay, status: :created, location: @stay }
      else
        format.html { render action: "new" }
        format.json { render json: @stay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stays/1
  # PUT /stays/1.json
  def update
    @stay = Stay.find(params[:id])

    respond_to do |format|
      if @stay.update_attributes(params[:stay])
        format.html { redirect_to @entrant, notice: 'Stay was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stays/1
  # DELETE /stays/1.json
  def destroy
    @stay = Stay.find(params[:id])
    @stay.destroy

    respond_to do |format|
      format.html { redirect_to stays_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/entrants_helper.rb
module EntrantsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/helpers/stays_helper.rb
module StaysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intake</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<script type="text/javascript">
  $(document).ready(function() {
    $('div.pop').each(function() {
      $(this).qtip({
        content: $('#hide-' + $(this).attr('id')),
        style: {
          name: 'cream'
},        
        position: {
        corner: {
         target: 'topMiddle',
         tooltip: 'bottomLeft'
      }
},
        show: 'mouseover',
        hide: 'mouseout'

      });
    });
  });   
</script>



<body>
    <div class="navbar"> 
      <div class="navbar-inner">
    	 	<div class="container">      	
      	 <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<%= link_to "HHM Intake", root_path, class: "brand" %>

		   	<div class="navbar-form pull-left">
			    <%= form_tag "/schoolssearch", :method => 'get' do %>  
      		  <%= text_field_tag :search, params[:search], :class=>'input-medium search-query' %>  
        		<%= submit_tag "Search", :name => nil, :class=>'btn' %>  
    			<% end %>
    		
    		</div>

 				 <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i><%= session[:username] %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Sign Out', logout_path %></li>
            </ul>
          </div>
          
      			<div class="nav-collapse collapse">
         			<ul class="nav">
          			<li><%= link_to 'Entrants', entrants_path %></li>
          			<li><%= link_to 'Shelters', shelters_path %></li>
          			<li><%= link_to 'Schools', schools_path %></li>
        			</ul>
        		</div>
        
        </div><!--container-->
      </div><!--navbar inner-->
    </div> <!--navbar-->
    
<div id="page">

<div class="container-fluid">
  <div class="row-fluid">
  
  	<div class="span3 sidebar-width">
  	  <div class="well sidebar-nav-fixed">
	    <div id="sidebar">
	      <ul class="nav nav-list">
	      	<li class="nav-header">Tables</li>
					<li><%= link_to 'Entrants', entrants_path %></li>
					<li><%= link_to 'Schools', schools_path %></li>
					<li><%= link_to 'Shelters', shelters_path %></li>
	        <li class="nav-header">Add A New</li>
	        <li><%= link_to 'Entrant', new_contact_path %></li>
          <li><%= link_to 'School', new_school_path %></li>
          <li><%= link_to 'Shelter', new_shelter_path %></li>
          <li class="nav-header">Reports</li>
	        <li><%= link_to 'Run a Report', reports_path %></li>
		  	</ul>
      </div> <!--Sidebar-->
      </div> <!--Sidebar well-->
		</div> <!--Span-->
    <div class="span9">

			<%= yield %>
    </div><!--Span-->
    
        </div>
</div>


<footer>
	<div class="navbar navbar-fixed-bottom">
  <!--  <p>&copy; Company 2012</p>-->
  </div>
</footer>
</div>

      
</body>
</html>